### PR TITLE
add missing images with correct folder paths

### PR DESCRIPTION
**Pull request by MOhammedRiaad**
I found images not working in the production due to missing images folder

### CODE REVIEW

**Review by mohamednajiub — CHANGES_REQUESTED** [review]
Hi, @MOhammedRiaad 
before i can accept your PR you need to pull the new changes from the master branch because your PR doesn't contains the new changes like new favicon and logo

**Comment by MOhammedRiaad** [comment]
Ok i will get the latest version and resubmit my files again.

**Comment by MOhammedRiaad** [comment]
Have updated my branch with the latest from Master , now you can accept my changes

**Comment by mohamednajiub** [comment]
Good Job @MOhammedRiaad

**Pull request merged**
